### PR TITLE
(Draft) Syntax of Mini-Elevate

### PR DESCRIPTION
**Pull request by roger-uw**

### CODE REVIEW

**Comment by Bastacyclop** [comment]
@roger-uw how do we look at the rendered result?

**Comment by Bastacyclop** [comment]
it also looks like you deleted the LICENSE

**Comment by michel-steuwer** [comment]
This can be tested with
```
bundler install
bundle exec jekyll serve
```

**Review by michel-steuwer — APPROVED** [review]
Looks like a good start!

**Pull request merged**
